"""initial schema

Revision ID: 0658fdbb3009
Revises: 
Create Date: 2026-09-21 15:37:15.899447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0658fdbb3009'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=True)
    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_categories_name'), 'expense_categories', ['name'], unique=True)
    op.create_table('farm_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_name', sa.String(length=160), nullable=False),
    sa.Column('owner_name', sa.String(length=160), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('low_feed_threshold_bags', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('high_mortality_rate_percent', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('budget_warning_percent', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('default_bag_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('default_bag_weight_kg > 0', name='ck_feedtype_bag_weight_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_types_name'), 'feed_types', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('ADMIN', 'MANAGER', 'STAFF', name='rolename', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_display', sa.String(length=120), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'RESTORE', name='activityaction', native_enum=False, length=20), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index('ix_activity_module_created', 'activity_logs', ['module', 'created_at'], unique=False)
    op.create_table('bird_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(length=40), nullable=False),
    sa.Column('breed', sa.String(length=80), nullable=False),
    sa.Column('initial_quantity', sa.Integer(), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=True),
    sa.Column('age_days_at_acquisition', sa.Integer(), nullable=False),
    sa.Column('cost_per_bird', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('adjustment_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD_OUT', 'CLOSED', name='batchstatus', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('adjustment_quantity >= 0', name='ck_batch_adjustment_non_negative'),
    sa.CheckConstraint('cost_per_bird >= 0', name='ck_batch_cost_non_negative'),
    sa.CheckConstraint('initial_quantity > 0', name='ck_batch_initial_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_status_date', 'bird_batches', ['status', 'acquisition_date'], unique=False)
    op.create_index(op.f('ix_bird_batches_acquisition_date'), 'bird_batches', ['acquisition_date'], unique=False)
    op.create_index(op.f('ix_bird_batches_batch_code'), 'bird_batches', ['batch_code'], unique=True)
    op.create_index(op.f('ix_bird_batches_is_deleted'), 'bird_batches', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_bird_batches_status'), 'bird_batches', ['status'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_budget_amount_non_negative'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_budget_period', 'budgets', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_budgets_is_active'), 'budgets', ['is_active'], unique=False)
    op.create_index(op.f('ix_budgets_is_deleted'), 'budgets', ['is_deleted'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('vendor', sa.String(length=160), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'MOBILE_MONEY', 'BANK_TRANSFER', 'CHEQUE', 'CREDIT', 'OTHER', name='paymentmethod', native_enum=False, length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=80), nullable=True),
    sa.Column('receipt_url', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('MANUAL', 'BIRD_BATCH', 'FEED_PURCHASE', 'HEALTH_RECORD', name='expensesource', native_enum=False, length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_expense_amount_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expense_date_category', 'expenses', ['expense_date', 'category_id'], unique=False)
    op.create_index('ix_expense_source', 'expenses', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_is_deleted'), 'expenses', ['is_deleted'], unique=False)
    op.create_table('feed_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_type_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('quantity_bags', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bag_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_per_bag', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('supplier', sa.String(length=160), nullable=True),
    sa.Column('lot_number', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('bag_weight_kg > 0', name='ck_purchase_weight_positive'),
    sa.CheckConstraint('cost_per_bag >= 0', name='ck_purchase_cost_non_negative'),
    sa.CheckConstraint('quantity_bags > 0', name='ck_purchase_bags_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feed_type_id'], ['feed_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feed_purchase_type_date', 'feed_purchases', ['feed_type_id', 'purchase_date'], unique=False)
    op.create_index(op.f('ix_feed_purchases_feed_type_id'), 'feed_purchases', ['feed_type_id'], unique=False)
    op.create_index(op.f('ix_feed_purchases_is_deleted'), 'feed_purchases', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_feed_purchases_purchase_date'), 'feed_purchases', ['purchase_date'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('FEED_LOW', 'FEED_UPDATED', 'MORTALITY_HIGH', 'MORTALITY_RECORDED', 'BUDGET_WARNING', 'BUDGET_EXCEEDED', 'HEALTH_ALERT', 'SALE_COMPLETED', 'BIRDS_ADDED', 'SYSTEM', name='notificationtype', native_enum=False, length=30), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'CRITICAL', name='notificationseverity', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_read_created', 'notifications', ['is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_dedupe_key'), 'notifications', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('feed_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_type_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('consumption_date', sa.Date(), nullable=False),
    sa.Column('quantity_bags', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('quantity_kg > 0', name='ck_consumption_kg_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['bird_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feed_type_id'], ['feed_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_consumption_batch_id'), 'feed_consumption', ['batch_id'], unique=False)
    op.create_index(op.f('ix_feed_consumption_consumption_date'), 'feed_consumption', ['consumption_date'], unique=False)
    op.create_index(op.f('ix_feed_consumption_feed_type_id'), 'feed_consumption', ['feed_type_id'], unique=False)
    op.create_index(op.f('ix_feed_consumption_is_deleted'), 'feed_consumption', ['is_deleted'], unique=False)
    op.create_index('ix_feed_consumption_type_date', 'feed_consumption', ['feed_type_id', 'consumption_date'], unique=False)
    op.create_table('health_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('sick_count', sa.Integer(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.String(length=200), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('medicine', sa.String(length=160), nullable=True),
    sa.Column('dosage', sa.String(length=120), nullable=True),
    sa.Column('treatment_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('veterinarian', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('SICK', 'UNDER_TREATMENT', 'RECOVERED', 'CRITICAL', name='healthstatus', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('sick_count > 0', name='ck_health_sick_positive'),
    sa.CheckConstraint('treatment_cost >= 0', name='ck_health_cost_non_negative'),
    sa.ForeignKeyConstraint(['batch_id'], ['bird_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_batch_status', 'health_records', ['batch_id', 'status'], unique=False)
    op.create_index(op.f('ix_health_records_batch_id'), 'health_records', ['batch_id'], unique=False)
    op.create_index(op.f('ix_health_records_is_deleted'), 'health_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_health_records_record_date'), 'health_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_health_records_status'), 'health_records', ['status'], unique=False)
    op.create_table('mortality_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cause', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='ck_mortality_quantity_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['bird_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mortality_batch_date', 'mortality_records', ['batch_id', 'record_date'], unique=False)
    op.create_index(op.f('ix_mortality_records_batch_id'), 'mortality_records', ['batch_id'], unique=False)
    op.create_index(op.f('ix_mortality_records_is_deleted'), 'mortality_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_mortality_records_record_date'), 'mortality_records', ['record_date'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('PAID', 'PARTIAL', 'UNPAID', 'CANCELLED', name='paymentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'MOBILE_MONEY', 'BANK_TRANSFER', 'CHEQUE', 'CREDIT', 'OTHER', name='paymentmethod', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount_paid >= 0', name='ck_sale_paid_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_sale_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sale_price_non_negative'),
    sa.ForeignKeyConstraint(['batch_id'], ['bird_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_batch_date', 'sales', ['batch_id', 'sale_date'], unique=False)
    op.create_index(op.f('ix_sales_batch_id'), 'sales', ['batch_id'], unique=False)
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_is_deleted'), 'sales', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sales_payment_status'), 'sales', ['payment_status'], unique=False)
    op.create_index(op.f('ix_sales_reference'), 'sales', ['reference'], unique=True)
    op.create_index(op.f('ix_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_sale_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_reference'), table_name='sales')
    op.drop_index(op.f('ix_sales_payment_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_is_deleted'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_batch_id'), table_name='sales')
    op.drop_index('ix_sale_batch_date', table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_mortality_records_record_date'), table_name='mortality_records')
    op.drop_index(op.f('ix_mortality_records_is_deleted'), table_name='mortality_records')
    op.drop_index(op.f('ix_mortality_records_batch_id'), table_name='mortality_records')
    op.drop_index('ix_mortality_batch_date', table_name='mortality_records')
    op.drop_table('mortality_records')
    op.drop_index(op.f('ix_health_records_status'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_record_date'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_is_deleted'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_batch_id'), table_name='health_records')
    op.drop_index('ix_health_batch_status', table_name='health_records')
    op.drop_table('health_records')
    op.drop_index('ix_feed_consumption_type_date', table_name='feed_consumption')
    op.drop_index(op.f('ix_feed_consumption_is_deleted'), table_name='feed_consumption')
    op.drop_index(op.f('ix_feed_consumption_feed_type_id'), table_name='feed_consumption')
    op.drop_index(op.f('ix_feed_consumption_consumption_date'), table_name='feed_consumption')
    op.drop_index(op.f('ix_feed_consumption_batch_id'), table_name='feed_consumption')
    op.drop_table('feed_consumption')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_dedupe_key'), table_name='notifications')
    op.drop_index('ix_notification_read_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_feed_purchases_purchase_date'), table_name='feed_purchases')
    op.drop_index(op.f('ix_feed_purchases_is_deleted'), table_name='feed_purchases')
    op.drop_index(op.f('ix_feed_purchases_feed_type_id'), table_name='feed_purchases')
    op.drop_index('ix_feed_purchase_type_date', table_name='feed_purchases')
    op.drop_table('feed_purchases')
    op.drop_index(op.f('ix_expenses_is_deleted'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_index('ix_expense_source', table_name='expenses')
    op.drop_index('ix_expense_date_category', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_budgets_is_deleted'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_is_active'), table_name='budgets')
    op.drop_index('ix_budget_period', table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_bird_batches_status'), table_name='bird_batches')
    op.drop_index(op.f('ix_bird_batches_is_deleted'), table_name='bird_batches')
    op.drop_index(op.f('ix_bird_batches_batch_code'), table_name='bird_batches')
    op.drop_index(op.f('ix_bird_batches_acquisition_date'), table_name='bird_batches')
    op.drop_index('ix_batch_status_date', table_name='bird_batches')
    op.drop_table('bird_batches')
    op.drop_index('ix_activity_module_created', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_feed_types_name'), table_name='feed_types')
    op.drop_table('feed_types')
    op.drop_table('farm_settings')
    op.drop_index(op.f('ix_expense_categories_name'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
